services:
  - type: web
    name: game-screenshot-classifier
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    runtime: python3
    region: oregon
    build:
      pythonVersion: 3.10.13
    autoDeploy: true
